# Generated by Django 4.1.2 on 2022-10-05 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAHASISWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.CharField(max_length=50)),
                ('NAMA', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('PHOTO', models.CharField(max_length=40)),
                ('EMAIL', models.CharField(max_length=40)),
                ('FAKULTAS', models.CharField(max_length=40)),
                ('PRODI', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='STAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=50)),
                ('NAMA', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('PHOTO', models.CharField(max_length=40)),
                ('EMAIL', models.CharField(max_length=40)),
                ('UNIT', models.CharField(max_length=40)),
                ('ALAMAT', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='dosen',
            name='MAHASISWA_id',
            field=models.ForeignKey(db_column='MAHASISWA_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_MAHASISWA_id', to='profil.mahasiswa'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='STAF_id',
            field=models.ForeignKey(db_column='STAF_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_STAF_id', to='profil.staf'),
        ),
    ]
